config/routes.rb
get "/issues/:id/answer/:to_user_id" => "issues#answer", as: :issues_answer

app/views/issues/_css.html.erb
<% if @issue %>
  <%= stylesheet_link_tag 'mentions.css', :plugin => 'journal_user_tags' %>
<% end %>

app/views/issues/_issue_answer_button.html.erb
<% last_user = issue.journals.order(:created_on).last.try(:user) %>
<% issue.answer_to_users_for(User.current).each do |answer_to_user| %>
  <%= link_to l("button_issue_answer", user_name: answer_to_user.name), issues_answer_path(id: issue.id, to_user_id: answer_to_user.id), class: "icon icon-comment button-positive" %>
<% end %>  

app/views/issues/_js.html.erb
<% if @issue %>
  <%= javascript_include_tag 'mention.js', :plugin => 'journal_user_tags' %>
  <script type="text/javascript">
    $(document).ready(function(){
      $(".primary-actions a").click(function(){
        mentionInterval = window.setInterval(function(){
          if (typeof(CKEDITOR) != "undefined"){
            $('#issue_notes').mentions();
            window.clearInterval(mentionInterval);
          }
        }, 250);
      });
     })
  </script>
<% end %>

app/views/issues/_js_css.html.erb
<% if @issue %>
  <%= javascript_include_tag 'mention.js', :plugin => 'journal_user_tags' %>
  <%= stylesheet_link_tag 'mentions.css', :plugin => 'journal_user_tags' %>
  <script type="text/javascript">
    $(document).ready(function(){
      window.setTimeout(function(){
        $('#issue_notes').mentions();
        console.log("yay")
      }, 1000);

     })
  </script>
<% end %>

app/views/issues/_mention.html.erb
<ul class="users_mentions_list">
  <% @issue.project.members.sort_by {|m| m.user.login.downcase }.each do |member| %>
    <li id="user_mentions" class="hide" tabindex: "0"><%= member.user.login.downcase %></li>
  <% end %>
</ul>